[theme]
base = "dark"
primaryColor = "#3B82F6"
backgroundColor = "#020617"
secondaryBackgroundColor = "#0F172A"
textColor = "#F8FAFC"
font = "sans serif"

[client]
toolbarMode = "minimal"
showSidebarNavigation = false

[server]
runOnSave = true
headless = true
